# Generated by Django 4.2.15 on 2024-08-14 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
    ]
