# Generated by Django 4.2.15 on 2024-08-14 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20240814_0147'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('1', 'Show Musical'), ('2', 'Peça de Teatro'), ('3', 'Palestra'), ('4', 'Orquestra'), ('5', 'Stand-up Comedy'), ('6', 'Show de Mágica'), ('7', 'Show de Dança'), ('8', 'Outro')], default='8', max_length=2),
        ),
    ]
