# Generated by Django 4.2.15 on 2024-08-14 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='final_date',
        ),
        migrations.RemoveField(
            model_name='event',
            name='initial_date',
        ),
        migrations.AddField(
            model_name='event',
            name='date_range',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
