# Generated by Django 4.2.15 on 2024-08-14 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_remove_event_final_date_remove_event_initial_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='date_range',
        ),
        migrations.AddField(
            model_name='event',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
